### ISSUE TITLE
older Anki version support

### ISSUE THREAD

**Issue by cyphar** [Ajatt-Tools/RefoldEase#3]
Quite a few folks are on Anki 2.1.22, so maybe we should handle older Anki versions nicely? Right now the add-on dies at:

```
Caught exception:
Traceback (most recent call last):
  File "C:\Users\Josh\AppData\Roaming\Anki2\addons21\RefoldEase\__init__.py", line 249, in onConfirm
    updateGroups(self.easeSpinBox.value(), self.imSpinBox.value())
  File "C:\Users\Josh\AppData\Roaming\Anki2\addons21\RefoldEase\__init__.py", line 90, in updateGroups
    dconfs = mw.col.decks.all_config()
AttributeError: 'DeckManager' object has no attribute 'all_config'
```

Because `all_config` was added in a later Anki release (but `allConf` existed before). Then again, most people will update once the Migaku add-ons are updated to the latest Anki version.

**Comment by tatsumoto-ren** [comment]
They should update as soon as possible and delete the Migaku add-ons.
